version: '3.7'

services:
  notification_react:
    image: notification_react
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - notification-app
  notification_server:
    image: notification_server
    ports:
      - "5000:5000"
    networks:
      - notification-app
networks:
  notification-app:
    driver: bridge
